<?php 

$categorys = $this->category;

?>


<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Category</title>
	<link rel="stylesheet" type="text/css" href="View/skin/style.css">
</head>
<body>
	<?php require_once 'View/html/header.phtml'; ?>
	<div class="content-main">
		<div class="content">
			<h2>Manage Category</h2>
			<a href="<?php print_r($url->getUrl('add'));?>">Add Category</a>
		</div>
		<div>
			<table border="2px" width="100%">
				<tr>
					<th>CategoryID</th>
					<th>Name</th>
					<th>Status</th>
					<th>CreatedAT</th>
					<th>UpdatedAT</th>
					<th colspan="2">Actions</th>
				</tr>
				<?php if(is_array($categorys)): ?>
					<?php foreach ($categorys as $category):?>
						<tr>
							<td><center><?php echo $category->category_id; ?></center></td>
							<td><?php echo $category->getPathText(); ?></td>
							<td><?php echo $category->getStatusText() ?></td>
							<td><?php echo $category->created_at; ?></td>
							<td><?php echo $category->updated_at; ?>
							</td>
							<td><a href="<?php print_r($url->getUrl('edit',Null,['id'=>$category->category_id])); ?>">Edit</a></td>
							<td><a href="<?php print_r($url->getUrl('delete',Null,['id'=>$category->category_id])); ?>">Delete</a></td>
						</tr>
					<?php endforeach; ?>
				<?php else: ?>
					<tr>
						<td colspan="9">Don't have any category.</td>
					</tr>
				<?php endif; ?>
			</table>
		</div>
	</div>
	<?php require_once 'View/html/footer.phtml'; ?>
</body>
</html>