<?php 

$product = $this->product;

?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<link rel="stylesheet" type="text/css" href="View/skin/style.css">

</head>
<body>
	<?php require_once 'View/html/header.phtml'; ?>
	<div class="content-main">
		<form action="<?php print_r($url->getUrl('save')); ?>" method="post">
			<table>
				<tr>
					<td>
						<h1>Save Product</h1>
					</td>
					<td class="sub-head">
						<button type="submit">Save</button>
	                    <input type="button" value="Cancel" onclick="window.location.href='<?php print_r($url->getUrl('grid',Null,Null,true)); ?>'">
					</td>
				</tr>
			</table>
			<table border="2px">
				<tr>
					<td>Name: </td>
					<td><input type="text" name="product[name]" value="<?php echo $product->name; ?>"></td>
				</tr>
				<tr>
					<td>SKU: </td>
					<td><input type="text" name="product[sku]" value="<?php echo $product->sku; ?>"></td>
				</tr>
				<tr>
					<td>Cost: </td>
					<td><input type="number" name="product[cost]" value="<?php echo $product->cost; ?>"></td>
				</tr>
				<tr>
					<td>price: </td>
					<td><input type="number" name="product[price]" value="<?php echo $product->price; ?>"></td>
				</tr>
				<tr>
					<td>Description: </td>
					<td><textarea name="product[description]"><?php echo $product->description; ?></textarea></td>
				</tr>
				<tr>
					<td>Status: </td>
					<td>
						<select name="product[status]">
							<?php foreach ($product->getTable()->getStatusOptions() as $key => $value): ?>
							<?php $selected = ($key == $product->getStatus()) ? 'selected':'' ?>
							<option value="<?php echo $key; ?>" <?php echo $selected; ?>><?php echo $value ?></option>
							<?php endforeach; ?>
						</select>
					</td>
				</tr>
				<tr>
					<td>Color: </td>
					<td><input type="text" name="product[color]" value="<?php echo $product->color; ?>"></td>
				</tr>
				<tr>
					<td>Material: </td>
					<td><input type="text" name="product[material]" value="<?php echo $product->material; ?>"></td>
				</tr>
			</table>
		</form>
	</div>
	<?php require_once 'View/html/footer.phtml'; ?>
</body>
</html>