<?php 

$customers = $this->customers;

?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
    <link rel="stylesheet" type="text/css" href="View/skin/style.css">

</head>
<body>
	<?php require_once 'View/html/header.phtml'; ?>
	<div class="content-main">
        <div class="content">
            <h2>Manage Customer</h2>
            <a href="<?php print_r($url->getUrl('add')); ?>">Add Customer</a>
        </div>
        <div>
            <table border="1px" width="100%">
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Gender</th>
                    <th>Mobile</th>
                    <th>Status</th>
                    <th>City</th>
                    <th>Country</th>
                    <th>CreatedAt</th>
                    <th>UpdatedAt</th>
                    <th colspan="2">Actions</th>
                </tr>
                <?php if(is_array($customers)): ?>
                    <?php foreach($customers as $customer):?>
                    <tr>
                        <td><center><?php echo $customer->customer_id; ?></center></td>
                        <td><?php echo $customer->first_name; ?></td>
                        <td><?php echo $customer->last_name; ?></td>
                        <td><?php echo $customer->email; ?></td>
                        <td><?php echo $customer->gender; ?></td>
                        <td><?php echo $customer->mobile; ?></td>
                        <td><?php echo $customer->getStatusText() ?></td>
                        <td><?php echo $customer->city; ?></td>
                        <td><?php echo $customer->country; ?></td>
                        <td><?php echo $customer->created_at; ?></td>
                        <td><?php echo $customer->updated_at;?></td>
                        <td><a href="<?php print_r($url->getUrl('edit',Null,['id'=>$customer->customer_id])); ?>">Edit</a></td>
                        <td><a href="<?php print_r($url->getUrl('delete',Null,['id'=>$customer->customer_id])); ?>">Delete</a></tD>
                    </tr>
                    <?php endforeach; ?>
                <?php else: ?>
                    <tr>
                        <td colspan="13">No records available.</td>
                    </tr>
                <?php endif; ?>
            </table>
        </div>
    </div>
	<?php require_once 'View/html/footer.phtml'; ?>
</body>
</html>