<?php 

$admin = $this->getData();

?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<link rel="stylesheet" type="text/css" href="View/skin/style.css">

</head>
<body>
	<?php require_once 'View/html/header.phtml'; ?>
	<div class="content-main">
		<form action="<?php print_r($url->getUrl('save')); ?>" method="post">
			<table>
				<tr>
					<td>
						<h1>Save Admin</h1>
					</td>
					<td class="sub-head">
						<button type="submit">Save</button>
	                    <input type="button" value="Cancel" onclick="window.location.href='<?php print_r($url->getUrl('grid',Null,Null,true)); ?>'">
					</td>
				</tr>
			</table>
			<table border="2px">
				<tr>
					<td>Name: </td>
					<td><input type="text" name="admin[name]" value="<?php echo $admin->name; ?>"></td>
				</tr>
				<tr>
					<td>Email: </td>
					<td><input type="text" name="admin[email]" value="<?php echo $admin->email; ?>"></td>
				</tr>
				<tr>
					<td>Password: </td>
					<td><input type="Password" name="admin[password]" value="<?php echo $admin->password; ?>"></td>
				</tr>
				<tr>
					<td>Status: </td>
					<td>
						<select name="admin[status]">
							<?php foreach ($admin->getTable()->getStatusOptions() as $key => $value): ?>
							<?php $selected = ($key == $admin->getStatus()) ? 'selected':'' ?>
							<option value="<?php echo $key; ?>" <?php echo $selected; ?>><?php echo $value ?></option>
							<?php endforeach; ?>
						</select>
					</td>
				</tr>
			</table>
		</form>
	</div>
	<?php require_once 'View/html/footer.phtml'; ?>
</body>
</html>