<style>
	.header{
		border: 2px solid white ;
		background-color: grey;
		height: 20px;
		padding: 20px 10px;
	}
	.header a {
    	text-decoration: none;
    	color: black;
    	padding: 0px 20px;
	}
	.message{
		padding: 10px;
		margin: 5px;
	}
	.failure{
		background-color: red;
	}
	.success{
		background-color: lightgreen;
	}
	.notice{
		background-color: orange;
	}
</style>

<div class="header">
	<a href="<?php print_r($url->getUrl('grid','product')); ?>">Product</a>
	<a href="<?php print_r($url->getUrl('grid','category')); ?>">Category</a>
	<a href="<?php print_r($url->getUrl('grid','customer')); ?>">Customer</a>
	<a href="<?php print_r($url->getUrl('grid','vendor')); ?>">Vendor</a>
	<a href="<?php print_r($url->getUrl('grid','salesman')); ?>">Salesman</a>
	<a href="<?php print_r($url->getUrl('grid','shipping')); ?>">Shipping Method</a>
	<a href="<?php print_r($url->getUrl('grid','payment')); ?>">Payment Method</a>
	<a href="<?php print_r($url->getUrl('grid','admin')); ?>">Admin</a>
</div>

<div>
	<?php

		$messageObject = Ccc::getModel('Core_Message');
		$messages = $messageObject->getMessage();
		if($messages){
			foreach ($messages as $type => $message) 
			{
				echo "<div class='message $type' >";
					echo $message;
					$messageObject->clearMessage();
				echo "</div>";
			}

		} 
	?>
</div>